# Generated by Django 4.0.4 on 2022-04-27 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('subgroup', models.CharField(max_length=5)),
                ('education_type', models.IntegerField(choices=[(0, 'Очное'), (1, 'Заочное')])),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='years.year')),
            ],
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('year', 'group', 'subgroup', 'education_type'), name='unique_group'),
        ),
    ]
