# Generated by Django 4.0.4 on 2022-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
