# Generated by Django 4.0.4 on 2022-05-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['education_type', 'stream', 'group_number', 'subgroup'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
