# Generated by Django 4.0.4 on 2022-04-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0002_alter_year_options_alter_year_year'),
        ('groups', '0002_alter_group_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='group',
            name='education_type',
            field=models.IntegerField(choices=[(0, 'Очное'), (1, 'Заочное')], verbose_name='Тип обучения'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.PositiveSmallIntegerField(verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subgroup',
            field=models.CharField(max_length=5, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='group',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='years.year', verbose_name='Поток'),
        ),
    ]
