# Generated by Django 4.0.4 on 2022-05-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name', 'first_name', 'patronymic'], 'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
    ]
