# Generated by Django 4.0.4 on 2022-05-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['name'], 'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
    ]
