# Generated by Django 4.0.4 on 2022-05-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievements', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('vk_link', models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка на ВК')),
                ('git_link', models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка на GitHub/GitLab')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.PositiveSmallIntegerField(choices=[(0, 'Не обещано/выдано'), (1, 'Обещано'), (2, 'Выдано')], verbose_name='Отношение')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement', verbose_name='Достижение')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Достижение студента',
                'verbose_name_plural': 'Достижения студента',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='achievements',
            field=models.ManyToManyField(through='students.StudentAchievement', to='achievements.achievement'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Группа'),
        ),
        migrations.AddConstraint(
            model_name='studentachievement',
            constraint=models.UniqueConstraint(fields=('student', 'achievement'), name='unique_student-achievement_relation'),
        ),
    ]
