# Generated by Django 4.0.4 on 2022-04-27 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100)),
                ('vk_link', models.CharField(blank=True, max_length=250)),
                ('git_link', models.CharField(blank=True, max_length=250)),
                ('promised_achievements', models.CharField(blank=True, max_length=500)),
                ('acquired_achievements', models.CharField(blank=True, max_length=500)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
    ]
