# Generated by Django 4.0.4 on 2022-04-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.PositiveSmallIntegerField(choices=[(0, 'Обещано'), (1, 'Выдано')])),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='acquired_achievements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='promised_achievements',
        ),
        migrations.AddField(
            model_name='student',
            name='achievements',
            field=models.ManyToManyField(through='students.Relation', to='achievements.achievement', verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='relation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
