# Generated by Django 4.0.4 on 2022-05-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name', 'patronymic', 'group'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='studentachievement',
            options={'ordering': ['student', 'relation'], 'verbose_name': 'Достижение студента', 'verbose_name_plural': 'Достижения студента'},
        ),
    ]
