# Generated by Django 4.0.4 on 2022-04-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('students', '0003_alter_relation_achievement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='achievements',
        ),
        migrations.AddField(
            model_name='student',
            name='acquired_achievements',
            field=models.ManyToManyField(blank=True, related_name='acquired_achievements', to='achievements.achievement', verbose_name='Acquired'),
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
