# Generated by Django 4.0.4 on 2022-04-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_acquired_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='git_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='vk_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
