# Generated by Django 4.0.4 on 2022-04-30 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('students', '0004_remove_student_achievements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.PositiveSmallIntegerField(choices=[(0, 'Не обещано/выдано'), (1, 'Обещано'), (2, 'Выдано')], verbose_name='Отношение')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='acquired_achievements',
        ),
        migrations.AddField(
            model_name='student',
            name='achievements',
            field=models.ManyToManyField(through='students.Relation', to='achievements.achievement'),
        ),
        migrations.AddField(
            model_name='relation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(fields=('student', 'achievement'), name='unique_student-achievement_relation'),
        ),
    ]
