# Generated by Django 4.0.4 on 2022-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('students', '0004_alter_student_git_link_alter_student_vk_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='acquired_achievements',
            field=models.ManyToManyField(blank=True, related_name='acquired_by_students', to='achievements.achievement'),
        ),
        migrations.AlterField(
            model_name='student',
            name='promised_achievements',
            field=models.ManyToManyField(blank=True, related_name='promised_to_students', to='achievements.achievement'),
        ),
    ]
