# Generated by Django 4.0.4 on 2022-04-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('students', '0005_relation_remove_student_acquired_achievements_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relation',
            new_name='StudentAchievements',
        ),
    ]
