# Generated by Django 4.0.4 on 2022-05-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('students', '0006_rename_relation_studentachievements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAchievements',
            new_name='StudentAchievement',
        ),
        migrations.AlterModelOptions(
            name='studentachievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
    ]
