# Generated by Django 4.0.4 on 2022-05-17 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('students', '0007_rename_studentachievements_studentachievement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentachievement',
            options={'verbose_name': 'Достижение студента', 'verbose_name_plural': 'Достижения студента'},
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement', verbose_name='Достижение'),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Студент'),
        ),
    ]
