# Generated by Django 4.0.4 on 2022-04-27 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.PositiveSmallIntegerField(default=600)),
                ('autopass', models.PositiveSmallIntegerField(default=1000)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='years.year')),
            ],
        ),
    ]
