# Generated by Django 4.0.4 on 2022-04-27 06:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_score', models.PositiveSmallIntegerField()),
                ('deadline_score', models.PositiveSmallIntegerField()),
                ('handing_in_date', models.DateField(default=datetime.date.today)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('student_id', 'assignment_id', 'general_score', 'deadline_score', 'handing_in_date'), name='unique_score'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(check=models.Q(('general_score__lte', 100)), name='general_score_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(check=models.Q(('deadline_score__lte', 100)), name='deadline_score_lte_100'),
        ),
    ]
