# Generated by Django 4.0.4 on 2022-04-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='assignment_id',
            new_name='assignment',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='student_id',
            new_name='student',
        ),
    ]
