# Generated by Django 4.0.4 on 2022-05-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['assignment', 'student'], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
    ]
