# Generated by Django 4.0.4 on 2022-04-28 08:41

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_options_and_more'),
        ('assignments', '0003_alter_assignment_options_and_more'),
        ('scores', '0003_remove_score_general_score_lte_100_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterField(
            model_name='score',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='score',
            name='deadline_score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Оценка за дедлайн'),
        ),
        migrations.AlterField(
            model_name='score',
            name='general_score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Оценка за работу'),
        ),
        migrations.AlterField(
            model_name='score',
            name='handing_in_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата сдачи работы'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Студент'),
        ),
    ]
