# Generated by Django 4.0.4 on 2022-04-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': 'Поток', 'verbose_name_plural': 'Потоки'},
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.DateField(help_text='Формат: yyyy-01-01, где yyyy (например, 2021) – год зачисления', unique=True, verbose_name='Год зачисления'),
        ),
    ]
