# Generated by Django 4.0.4 on 2022-04-27 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateField()),
                ('assigned_to_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='years.year')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('name', 'description', 'deadline', 'assigned_to_year'), name='unique_assignment'),
        ),
    ]
