# Generated by Django 4.0.4 on 2022-04-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
