# Generated by Django 4.0.4 on 2022-04-28 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 5, 26), verbose_name='Дедлайн'),
        ),
    ]
