# Generated by Django 4.0.4 on 2022-04-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0002_alter_year_options_alter_year_year'),
        ('assignments', '0002_alter_assignment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_to_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='years.year', verbose_name='Поток'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateField(verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
