# Generated by Django 4.0.4 on 2022-04-28 18:08

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateField(default=assignments.models.default_deadline, verbose_name='Дедлайн'),
        ),
    ]
