# Generated by Django 4.0.4 on 2022-04-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.DateField(help_text='Формат: yyyy-01-01, где yyyy (например, 2021) – год зачисления', unique=True, verbose_name='Год зачисления')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
    ]
