# Generated by Django 4.0.4 on 2022-05-19 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='Год зачисления')),
                ('required', models.PositiveSmallIntegerField(default=600, verbose_name='Кол-во баллов для допуска к зачёту/экзамену')),
                ('autopass', models.PositiveSmallIntegerField(default=1000, verbose_name='Кол-во баллов для экзамена/зачёта автоматом')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
    ]
