# Generated by Django 4.0.4 on 2022-05-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['stream'], 'verbose_name': 'Поток', 'verbose_name_plural': 'Потоки'},
        ),
    ]
