# Generated by Django 4.0.4 on 2022-04-29 08:15

import datetime
import django.core.validators
from django.db import migrations, models
import streams.models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_alter_stream_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream',
            field=models.DateField(help_text='Формат: 20yy-01-01, где 20yy (например, 2021) – год зачисления', unique=True, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2099, 1, 1)), streams.models.validate_format], verbose_name='Год зачисления'),
        ),
    ]
