# Generated by Django 4.0.4 on 2022-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_alter_stream_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='autopass',
            field=models.PositiveSmallIntegerField(default=1000, verbose_name='Кол-во баллов для экзамена/зачёта автоматом'),
        ),
        migrations.AddField(
            model_name='stream',
            name='required',
            field=models.PositiveSmallIntegerField(default=600, verbose_name='Кол-во баллов для допуска к зачёту/экзамену'),
        ),
    ]
